"use client";
import { useActionState } from "react";
import { signIn, createWorkspace, createDecision, createWorkItem, createRequirement, createEvidence, createArtifact } from "@/app/workspaces/actions";
export function SignInForm() {
  const [state, action, pending] = useActionState(signIn, { error: "" });
  return <form action={action} className="durable-form"><label htmlFor="email">Email<input id="email" name="email" type="email" autoComplete="username" required maxLength={254} /></label><label htmlFor="password">Password<input id="password" name="password" type="password" autoComplete="current-password" required maxLength={1024} /></label>{state.error && <p role="alert" className="form-error">{state.error}</p>}<button className="button primary" type="submit" disabled={pending}>{pending ? "Signing in…" : "Sign in"}</button></form>;
}
export function CreateWorkspaceForm({ requestId }: { requestId: string }) {
  const [state, action, pending] = useActionState(createWorkspace, { error: "" });
  return <form action={action} className="durable-form"><input type="hidden" name="requestId" value={requestId} /><label htmlFor="name">Project name<input id="name" name="name" required maxLength={120} placeholder="Name your project" /></label><label htmlFor="problem">What problem do you want to solve?<textarea id="problem" name="problem" rows={4} required maxLength={2000} placeholder="Describe the problem and who experiences it." /></label><label htmlFor="release">Release name<input id="release" name="release" required maxLength={80} defaultValue="Release 1.0" /></label><p className="form-help">Your workspace starts at Clarify. No stages are marked complete.</p>{state.error && <p role="alert" className="form-error">{state.error}</p>}<button className="button primary" type="submit" disabled={pending}>{pending ? "Saving workspace…" : "Create workspace"}</button></form>;
}
export function CreateDecisionForm({ workspaceId, requestId }: { workspaceId: string; requestId: string }) {
  const [state, action, pending] = useActionState(createDecision, { error: "" });
  return <form action={action} className="durable-form"><input type="hidden" name="workspaceId" value={workspaceId} /><input type="hidden" name="requestId" value={requestId} /><label htmlFor="decision-title">Decision title<input id="decision-title" name="title" required maxLength={160} placeholder="Name the decision" /></label><label htmlFor="decision-statement">Decision statement<textarea id="decision-statement" name="decision" rows={4} required maxLength={4000} placeholder="State the approved product or business choice clearly." /></label><label htmlFor="decision-rationale">Why this decision?<textarea id="decision-rationale" name="rationale" rows={4} required maxLength={4000} placeholder="Record the reason, evidence, or tradeoff behind the choice." /></label><label className="owner-confirm" htmlFor="decision-authority"><input id="decision-authority" name="confirmAuthority" type="checkbox" required /><span>I confirm this is a product-scope or business decision within product-owner authority.</span></label><p className="form-help">Saving records this choice as Accepted. Do not use this action for a consequential technical decision that requires qualified specialist review.</p>{state.error && <p role="alert" className="form-error">{state.error}</p>}<button className="button primary" type="submit" disabled={pending}>{pending ? "Recording decision…" : "Record accepted decision"}</button></form>;
}
export function CreateWorkItemForm({ workspaceId, requestId }: { workspaceId: string; requestId: string }) {
  const [state, action, pending] = useActionState(createWorkItem, { error: "" });
  return <form action={action} className="durable-form"><input type="hidden" name="workspaceId" value={workspaceId} /><input type="hidden" name="requestId" value={requestId} /><label htmlFor="work-title">Work-item title<input id="work-title" name="title" required maxLength={160} placeholder="Name the bounded work" /></label><label htmlFor="work-outcome">Outcome<textarea id="work-outcome" name="outcome" rows={4} required maxLength={4000} placeholder="Describe the concrete output or result this work should produce." /></label><label htmlFor="work-complete">Complete when<textarea id="work-complete" name="completionCondition" rows={3} required maxLength={4000} placeholder="State the observable condition that makes this work complete." /></label><label htmlFor="work-evidence">Evidence expected<textarea id="work-evidence" name="evidenceExpectation" rows={3} required maxLength={4000} placeholder="Describe the result or record expected to support completion." /></label><p className="form-help">Saving creates proposed work owned by you. It does not start execution, assign a specialist, or claim implementation, review, or verification.</p>{state.error && <p role="alert" className="form-error">{state.error}</p>}<button className="button primary" type="submit" disabled={pending}>{pending ? "Saving proposed work…" : "Add proposed work item"}</button></form>;
}
export function CreateRequirementForm({ workspaceId, requestId }: { workspaceId: string; requestId: string }) {
  const [state, action, pending] = useActionState(createRequirement, { error: "" });
  return <form action={action} className="durable-form"><input type="hidden" name="workspaceId" value={workspaceId} /><input type="hidden" name="requestId" value={requestId} /><label htmlFor="requirement-title">Requirement title<input id="requirement-title" name="title" required maxLength={160} placeholder="Name the required product behavior" /></label><label htmlFor="requirement-obligation">Obligation<select id="requirement-obligation" name="obligation" aria-label="Obligation" defaultValue="MUST" required><option value="MUST">MUST — required behavior</option><option value="SHOULD">SHOULD — strong default</option><option value="MAY">MAY — optional behavior</option></select></label><label htmlFor="requirement-statement">Requirement statement<textarea id="requirement-statement" name="requirement" rows={4} required maxLength={4000} placeholder="State the product or business behavior clearly without adding a second obligation word." /></label><label htmlFor="acceptance-criterion">Acceptance criterion<textarea id="acceptance-criterion" name="acceptanceCriterion" rows={4} required maxLength={4000} placeholder="State one observable condition that determines whether the requirement is satisfied." /></label><label className="owner-confirm" htmlFor="requirement-authority"><input id="requirement-authority" name="confirmAuthority" type="checkbox" required /><span>I confirm this requirement states product or business behavior within product-owner authority. Consequential technical implementation choices remain subject to qualified specialist review.</span></label><p className="form-help">Saving records an Approved product requirement and one acceptance criterion. The criterion is not a test result and is not verification evidence.</p>{state.error && <p role="alert" className="form-error">{state.error}</p>}<button className="button primary" type="submit" disabled={pending}>{pending ? "Recording requirement…" : "Record approved requirement"}</button></form>;
}
export function CreateEvidenceForm({ workspaceId, acceptanceCriterionId, requestId }: { workspaceId: string; acceptanceCriterionId: string; requestId: string }) {
  const [state, action, pending] = useActionState(createEvidence, { error: "" });
  const suffix = acceptanceCriterionId.slice(0, 8);
  return <form action={action} className="durable-form evidence-form"><input type="hidden" name="workspaceId" value={workspaceId} /><input type="hidden" name="acceptanceCriterionId" value={acceptanceCriterionId} /><input type="hidden" name="requestId" value={requestId} /><label htmlFor={`evidence-title-${suffix}`}>Evidence title<input id={`evidence-title-${suffix}`} name="title" required maxLength={160} placeholder="Name the recorded result" /></label><label htmlFor={`evidence-effect-${suffix}`}>Effect on criterion<select id={`evidence-effect-${suffix}`} name="effect" aria-label="Effect on criterion" defaultValue="Supports" required><option value="Supports">Supports — result aligns with the criterion</option><option value="Challenges">Challenges — result conflicts with the criterion</option><option value="Inconclusive">Inconclusive — result does not establish either relationship</option></select></label><label htmlFor={`evidence-result-${suffix}`}>Result<textarea id={`evidence-result-${suffix}`} name="result" rows={4} required maxLength={4000} placeholder="Record what was observed, measured, tested, or returned." /></label><label htmlFor={`evidence-source-${suffix}`}>Source / provenance<textarea id={`evidence-source-${suffix}`} name="sourceNote" rows={3} required maxLength={2000} placeholder="State where this result came from so another person can judge its context." /></label><p className="form-help">Saving records evidence against this criterion. It does not mark the criterion satisfied, passed, verified, or validated, and it does not establish specialist review.</p>{state.error && <p role="alert" className="form-error">{state.error}</p>}<button className="button secondary" type="submit" disabled={pending}>{pending ? "Recording evidence…" : "Record evidence"}</button></form>;
}
export function CreateArtifactForm({ workspaceId, requestId }: { workspaceId: string; requestId: string }) {
  const [state, action, pending] = useActionState(createArtifact, { error: "" });
  return <form action={action} className="durable-form artifact-form"><input type="hidden" name="workspaceId" value={workspaceId} /><input type="hidden" name="requestId" value={requestId} /><label htmlFor="artifact-title">Artifact title<input id="artifact-title" name="title" required maxLength={160} placeholder="Name the project output" /></label><label htmlFor="artifact-kind">Artifact kind<input id="artifact-kind" name="kind" required maxLength={80} placeholder="For example: problem brief, design, requirement set" /></label><label htmlFor="artifact-summary">Summary<textarea id="artifact-summary" name="summary" rows={4} required maxLength={4000} placeholder="Describe what this proposed artifact contains and why it matters." /></label><label htmlFor="artifact-reference-label">Reference label<input id="artifact-reference-label" name="referenceLabel" required maxLength={160} placeholder="Name the external source" /></label><label htmlFor="artifact-reference-url">Reference URL<input id="artifact-reference-url" name="referenceUrl" type="url" required maxLength={2048} placeholder="https://…" /></label><p className="form-help">Saving creates version 1 as Proposed. It does not accept the artifact as project direction, claim review or verification, or fetch the referenced content.</p>{state.error && <p role="alert" className="form-error">{state.error}</p>}<button className="button secondary" type="submit" disabled={pending}>{pending ? "Recording artifact…" : "Record proposed artifact"}</button></form>;
}
