"use client";
import { useActionState } from "react";
import { signIn, createWorkspace, createDecision, createWorkItem } from "@/app/workspaces/actions";
export function SignInForm() {
  const [state, action, pending] = useActionState(signIn, { error: "" });
  return <form action={action} className="durable-form"><label htmlFor="email">Email<input id="email" name="email" type="email" autoComplete="username" required maxLength={254} /></label><label htmlFor="password">Password<input id="password" name="password" type="password" autoComplete="current-password" required maxLength={1024} /></label>{state.error && <p role="alert" className="form-error">{state.error}</p>}<button className="button primary" type="submit" disabled={pending}>{pending ? "Signing in…" : "Sign in"}</button></form>;
}
export function CreateWorkspaceForm({ requestId }: { requestId: string }) {
  const [state, action, pending] = useActionState(createWorkspace, { error: "" });
  return <form action={action} className="durable-form"><input type="hidden" name="requestId" value={requestId} /><label htmlFor="name">Project name<input id="name" name="name" required maxLength={120} placeholder="Name your project" /></label><label htmlFor="problem">What problem do you want to solve?<textarea id="problem" name="problem" rows={4} required maxLength={2000} placeholder="Describe the problem and who experiences it." /></label><label htmlFor="release">Release name<input id="release" name="release" required maxLength={80} defaultValue="Release 1.0" /></label><p className="form-help">Your workspace starts at Clarify. No stages are marked complete.</p>{state.error && <p role="alert" className="form-error">{state.error}</p>}<button className="button primary" type="submit" disabled={pending}>{pending ? "Saving workspace…" : "Create workspace"}</button></form>;
}
export function CreateDecisionForm({ workspaceId, requestId }: { workspaceId: string; requestId: string }) {
  const [state, action, pending] = useActionState(createDecision, { error: "" });
  return <form action={action} className="durable-form"><input type="hidden" name="workspaceId" value={workspaceId} /><input type="hidden" name="requestId" value={requestId} /><label htmlFor="decision-title">Decision title<input id="decision-title" name="title" required maxLength={160} placeholder="Name the decision" /></label><label htmlFor="decision-statement">Decision statement<textarea id="decision-statement" name="decision" rows={4} required maxLength={4000} placeholder="State the approved product or business choice clearly." /></label><label htmlFor="decision-rationale">Why this decision?<textarea id="decision-rationale" name="rationale" rows={4} required maxLength={4000} placeholder="Record the reason, evidence, or tradeoff behind the choice." /></label><label className="owner-confirm" htmlFor="decision-authority"><input id="decision-authority" name="confirmAuthority" type="checkbox" required /><span>I confirm this is a product-scope or business decision within product-owner authority.</span></label><p className="form-help">Saving records this choice as Accepted. Do not use this action for a consequential technical decision that requires qualified specialist review.</p>{state.error && <p role="alert" className="form-error">{state.error}</p>}<button className="button primary" type="submit" disabled={pending}>{pending ? "Recording decision…" : "Record accepted decision"}</button></form>;
}
export function CreateWorkItemForm({ workspaceId, requestId }: { workspaceId: string; requestId: string }) {
  const [state, action, pending] = useActionState(createWorkItem, { error: "" });
  return <form action={action} className="durable-form"><input type="hidden" name="workspaceId" value={workspaceId} /><input type="hidden" name="requestId" value={requestId} /><label htmlFor="work-title">Work-item title<input id="work-title" name="title" required maxLength={160} placeholder="Name the bounded work" /></label><label htmlFor="work-outcome">Outcome<textarea id="work-outcome" name="outcome" rows={4} required maxLength={4000} placeholder="Describe the concrete output or result this work should produce." /></label><label htmlFor="work-complete">Complete when<textarea id="work-complete" name="completionCondition" rows={3} required maxLength={4000} placeholder="State the observable condition that makes this work complete." /></label><label htmlFor="work-evidence">Evidence expected<textarea id="work-evidence" name="evidenceExpectation" rows={3} required maxLength={4000} placeholder="Describe the result or record expected to support completion." /></label><p className="form-help">Saving creates proposed work owned by you. It does not start execution, assign a specialist, or claim implementation, review, or verification.</p>{state.error && <p role="alert" className="form-error">{state.error}</p>}<button className="button primary" type="submit" disabled={pending}>{pending ? "Saving proposed work…" : "Add proposed work item"}</button></form>;
}
